#cloud-config
users: #Liste der Benutzer
  - name: ubuntu #Benutzername vom Benutzer
    sudo: ALL=(ALL) NOPASSWD:ALL #Sodass man sich ohne Passwort sudo-Befehle ausführen kann
    groups: users, admin #Gruppen des Benutzers
    home: /home/ubuntu #Home Directory vom Benutzer
    shell: /bin/bash #Shell vom Benutzer
    ssh_authorized_keys: #Public key vom Server
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key       
ssh_pwauth: false #Sorgt dafür, dass man das Passwort gar nicht braucht
disable_root: false #Deaktiviert root nicht
package_update: true #Erlaubt updates von packages
packages: #Liste der packages, die installiert werden sollen
  - curl 
  - wget 
